using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Kairos.Application.Country.Dtos;
using Nager.Date;

namespace Kairos.Application.Country
{
    public interface ICountryProvider
    {
        Task<IEnumerable<CountryModel>> GetCountries();
    }

    public class CountryProvider : ICountryProvider
    {
        private readonly ImmutableList<CountryModel> _countries;

        public CountryProvider()
        {
            _countries = GetAllCountries().ToImmutableList();
        }

        public async Task<IEnumerable<CountryModel>> GetCountries()
        {
            await Task.CompletedTask;

            return _countries;
        }

        private IEnumerable<CountryModel> GetAllCountries()
        {
            yield return new CountryModel(CountryCode.AD, "Andorra");
            yield return new CountryModel(CountryCode.AE, "United Arab Emirates");
            yield return new CountryModel(CountryCode.AF, "Afghanistan");
            yield return new CountryModel(CountryCode.AG, "Antigua and Barbuda");
            yield return new CountryModel(CountryCode.AI, "Anguilla");
            yield return new CountryModel(CountryCode.AL, "Albania");
            yield return new CountryModel(CountryCode.AM, "Armenia");
            yield return new CountryModel(CountryCode.AO, "Angola");
            yield return new CountryModel(CountryCode.AQ, "Antarctica");
            yield return new CountryModel(CountryCode.AR, "Argentina");
            yield return new CountryModel(CountryCode.AS, "American Samoa");
            yield return new CountryModel(CountryCode.AT, "Austria");
            yield return new CountryModel(CountryCode.AU, "Australia");
            yield return new CountryModel(CountryCode.AW, "Aruba");
            yield return new CountryModel(CountryCode.AX, "Åland Islands");
            yield return new CountryModel(CountryCode.AZ, "Azerbaijan");
            yield return new CountryModel(CountryCode.BA, "Bosnia and Herzegovina");
            yield return new CountryModel(CountryCode.BB, "Barbados");
            yield return new CountryModel(CountryCode.BD, "Bangladesh");
            yield return new CountryModel(CountryCode.BE, "Belgium");
            yield return new CountryModel(CountryCode.BF, "Burkina Faso");
            yield return new CountryModel(CountryCode.BG, "Bulgaria");
            yield return new CountryModel(CountryCode.BH, "Bahrain");
            yield return new CountryModel(CountryCode.BI, "Burundi");
            yield return new CountryModel(CountryCode.BJ, "Benin");
            yield return new CountryModel(CountryCode.BL, "Saint Barthélemy");
            yield return new CountryModel(CountryCode.BM, "Bermuda");
            yield return new CountryModel(CountryCode.BN, "Brunei Darussalam");
            yield return new CountryModel(CountryCode.BO, "Bolivia (Plurinational State of)");
            yield return new CountryModel(CountryCode.BQ, "Bonaire, Sint Eustatius and Saba");
            yield return new CountryModel(CountryCode.BR, "Brazil");
            yield return new CountryModel(CountryCode.BS, "Bahamas");
            yield return new CountryModel(CountryCode.BT, "Bhutan");
            yield return new CountryModel(CountryCode.BV, "Bouvet Island");
            yield return new CountryModel(CountryCode.BW, "Botswana");
            yield return new CountryModel(CountryCode.BY, "Belarus");
            yield return new CountryModel(CountryCode.BZ, "Belize");
            yield return new CountryModel(CountryCode.CA, "Canada");
            yield return new CountryModel(CountryCode.CC, "Cocos (Keeling) Islands");
            yield return new CountryModel(CountryCode.CD, "Congo (Democratic Republic of the)");
            yield return new CountryModel(CountryCode.CF, "Central African Republic");
            yield return new CountryModel(CountryCode.CG, "Congo");
            yield return new CountryModel(CountryCode.CH, "Switzerland");
            yield return new CountryModel(CountryCode.CI, "Côte d'Ivoire");
            yield return new CountryModel(CountryCode.CK, "Cook Islands");
            yield return new CountryModel(CountryCode.CL, "Chile");
            yield return new CountryModel(CountryCode.CM, "Cameroon");
            yield return new CountryModel(CountryCode.CN, "China");
            yield return new CountryModel(CountryCode.CO, "Colombia");
            yield return new CountryModel(CountryCode.CR, "Costa Rica");
            yield return new CountryModel(CountryCode.CU, "Cuba");
            yield return new CountryModel(CountryCode.CV, "Cabo Verde");
            yield return new CountryModel(CountryCode.CW, "Curaçao");
            yield return new CountryModel(CountryCode.CX, "Christmas Island");
            yield return new CountryModel(CountryCode.CY, "Cyprus");
            yield return new CountryModel(CountryCode.CZ, "Czech Republic");
            yield return new CountryModel(CountryCode.DE, "Germany");
            yield return new CountryModel(CountryCode.DJ, "Djibouti");
            yield return new CountryModel(CountryCode.DK, "Denmark");
            yield return new CountryModel(CountryCode.DM, "Dominica");
            yield return new CountryModel(CountryCode.DO, "Dominican Republic");
            yield return new CountryModel(CountryCode.DZ, "Algeria");
            yield return new CountryModel(CountryCode.EC, "Ecuador");
            yield return new CountryModel(CountryCode.EE, "Estonia");
            yield return new CountryModel(CountryCode.EG, "Egypt");
            yield return new CountryModel(CountryCode.EH, "Western Sahara");
            yield return new CountryModel(CountryCode.ER, "Eritrea");
            yield return new CountryModel(CountryCode.ES, "Spain");
            yield return new CountryModel(CountryCode.ET, "Ethiopia");
            yield return new CountryModel(CountryCode.FI, "Finland");
            yield return new CountryModel(CountryCode.FJ, "Fiji");
            yield return new CountryModel(CountryCode.FK, "Falkland Islands (Malvinas)");
            yield return new CountryModel(CountryCode.FM, "Micronesia (Federated States of)");
            yield return new CountryModel(CountryCode.FO, "Faroe Islands");
            yield return new CountryModel(CountryCode.FR, "France");
            yield return new CountryModel(CountryCode.GA, "Gabon");
            yield return new CountryModel(CountryCode.GB, "United Kingdom of Great Britain and Northern Ireland");
            yield return new CountryModel(CountryCode.GD, "Grenada");
            yield return new CountryModel(CountryCode.GE, "Georgia");
            yield return new CountryModel(CountryCode.GF, "French Guiana");
            yield return new CountryModel(CountryCode.GG, "Guernsey");
            yield return new CountryModel(CountryCode.GH, "Ghana");
            yield return new CountryModel(CountryCode.GI, "Gibraltar");
            yield return new CountryModel(CountryCode.GL, "Greenland");
            yield return new CountryModel(CountryCode.GM, "Gambia");
            yield return new CountryModel(CountryCode.GN, "Guinea");
            yield return new CountryModel(CountryCode.GP, "Guadeloupe");
            yield return new CountryModel(CountryCode.GQ, "Equatorial Guinea");
            yield return new CountryModel(CountryCode.GR, "Greece");
            yield return new CountryModel(CountryCode.GS, "South Georgia and the South Sandwich Islands");
            yield return new CountryModel(CountryCode.GT, "Guatemala");
            yield return new CountryModel(CountryCode.GU, "Guam");
            yield return new CountryModel(CountryCode.GW, "Guinea-Bissau");
            yield return new CountryModel(CountryCode.GY, "Guyana");
            yield return new CountryModel(CountryCode.HK, "Hong Kong");
            yield return new CountryModel(CountryCode.HM, "Heard Island and McDonald Islands");
            yield return new CountryModel(CountryCode.HN, "Honduras");
            yield return new CountryModel(CountryCode.HR, "Croatia");
            yield return new CountryModel(CountryCode.HT, "Haiti");
            yield return new CountryModel(CountryCode.HU, "Hungary");
            yield return new CountryModel(CountryCode.ID, "Indonesia");
            yield return new CountryModel(CountryCode.IE, "Ireland");
            yield return new CountryModel(CountryCode.IL, "Israel");
            yield return new CountryModel(CountryCode.IM, "Isle of Man");
            yield return new CountryModel(CountryCode.IN, "India");
            yield return new CountryModel(CountryCode.IO, "British Indian Ocean Territory");
            yield return new CountryModel(CountryCode.IQ, "Iraq");
            yield return new CountryModel(CountryCode.IR, "Iran (Islamic Republic of)");
            yield return new CountryModel(CountryCode.IS, "Iceland");
            yield return new CountryModel(CountryCode.IT, "Italy");
            yield return new CountryModel(CountryCode.JE, "Jersey");
            yield return new CountryModel(CountryCode.JM, "Jamaica");
            yield return new CountryModel(CountryCode.JO, "Jordan");
            yield return new CountryModel(CountryCode.JP, "Japan");
            yield return new CountryModel(CountryCode.KE, "Kenya");
            yield return new CountryModel(CountryCode.KG, "Kyrgyzstan");
            yield return new CountryModel(CountryCode.KH, "Cambodia");
            yield return new CountryModel(CountryCode.KI, "Kiribati");
            yield return new CountryModel(CountryCode.KM, "Comoros");
            yield return new CountryModel(CountryCode.KN, "Saint Kitts and Nevis");
            yield return new CountryModel(CountryCode.KP, "North Korea");
            yield return new CountryModel(CountryCode.KR, "South Korea");
            yield return new CountryModel(CountryCode.KW, "Kuwait");
            yield return new CountryModel(CountryCode.KY, "Cayman Islands");
            yield return new CountryModel(CountryCode.KZ, "Kazakhstan");
            yield return new CountryModel(CountryCode.LA, "Laos");
            yield return new CountryModel(CountryCode.LB, "Lebanon");
            yield return new CountryModel(CountryCode.LC, "Saint Lucia");
            yield return new CountryModel(CountryCode.LI, "Liechtenstein");
            yield return new CountryModel(CountryCode.LK, "Sri Lanka");
            yield return new CountryModel(CountryCode.LR, "Liberia");
            yield return new CountryModel(CountryCode.LS, "Lesotho");
            yield return new CountryModel(CountryCode.LT, "Lithuania");
            yield return new CountryModel(CountryCode.LU, "Luxembourg");
            yield return new CountryModel(CountryCode.LV, "Latvia");
            yield return new CountryModel(CountryCode.LY, "Libya");
            yield return new CountryModel(CountryCode.MA, "Morocco");
            yield return new CountryModel(CountryCode.MC, "Monaco");
            yield return new CountryModel(CountryCode.MD, "Moldova (Republic of)");
            yield return new CountryModel(CountryCode.ME, "Montenegro");
            yield return new CountryModel(CountryCode.MF, "Saint Martin (French part)");
            yield return new CountryModel(CountryCode.MG, "Madagascar");
            yield return new CountryModel(CountryCode.MH, "Marshall Islands");
            yield return new CountryModel(CountryCode.MK, "Macedonia (the former Yugoslav Republic of)");
            yield return new CountryModel(CountryCode.ML, "Mali");
            yield return new CountryModel(CountryCode.MM, "Myanmar");
            yield return new CountryModel(CountryCode.MN, "Mongolia");
            yield return new CountryModel(CountryCode.MO, "Macao");
            yield return new CountryModel(CountryCode.MP, "Northern Mariana Islands");
            yield return new CountryModel(CountryCode.MQ, "Martinique");
            yield return new CountryModel(CountryCode.MR, "Mauritania");
            yield return new CountryModel(CountryCode.MS, "Montserrat");
            yield return new CountryModel(CountryCode.MT, "Malta");
            yield return new CountryModel(CountryCode.MU, "Mauritius");
            yield return new CountryModel(CountryCode.MV, "Maldives");
            yield return new CountryModel(CountryCode.MW, "Malawi");
            yield return new CountryModel(CountryCode.MX, "Mexico");
            yield return new CountryModel(CountryCode.MY, "Malaysia");
            yield return new CountryModel(CountryCode.MZ, "Mozambique");
            yield return new CountryModel(CountryCode.NA, "Namibia");
            yield return new CountryModel(CountryCode.NC, "New Caledonia");
            yield return new CountryModel(CountryCode.NE, "Niger");
            yield return new CountryModel(CountryCode.NF, "Norfolk Island");
            yield return new CountryModel(CountryCode.NG, "Nigeria");
            yield return new CountryModel(CountryCode.NI, "Nicaragua");
            yield return new CountryModel(CountryCode.NL, "Netherlands");
            yield return new CountryModel(CountryCode.NO, "Norway");
            yield return new CountryModel(CountryCode.NP, "Nepal");
            yield return new CountryModel(CountryCode.NR, "Nauru");
            yield return new CountryModel(CountryCode.NU, "Niue");
            yield return new CountryModel(CountryCode.NZ, "New Zealand");
            yield return new CountryModel(CountryCode.OM, "Oman");
            yield return new CountryModel(CountryCode.PA, "Panama");
            yield return new CountryModel(CountryCode.PE, "Peru");
            yield return new CountryModel(CountryCode.PF, "French Polynesia");
            yield return new CountryModel(CountryCode.PG, "Papua New Guinea");
            yield return new CountryModel(CountryCode.PH, "Philippines");
            yield return new CountryModel(CountryCode.PK, "Pakistan");
            yield return new CountryModel(CountryCode.PL, "Poland");
            yield return new CountryModel(CountryCode.PM, "Saint Pierre and Miquelon");
            yield return new CountryModel(CountryCode.PN, "Pitcairn");
            yield return new CountryModel(CountryCode.PR, "Puerto Rico");
            yield return new CountryModel(CountryCode.PS, "Palestine, State of");
            yield return new CountryModel(CountryCode.PT, "Portugal");
            yield return new CountryModel(CountryCode.PW, "Palau");
            yield return new CountryModel(CountryCode.PY, "Paraguay");
            yield return new CountryModel(CountryCode.QA, "Qatar");
            yield return new CountryModel(CountryCode.RE, "Réunion");
            yield return new CountryModel(CountryCode.RO, "Romania");
            yield return new CountryModel(CountryCode.RS, "Serbia");
            yield return new CountryModel(CountryCode.RU, "Russian Federation");
            yield return new CountryModel(CountryCode.RW, "Rwanda");
            yield return new CountryModel(CountryCode.SA, "Saudi Arabia");
            yield return new CountryModel(CountryCode.SB, "Solomon Islands");
            yield return new CountryModel(CountryCode.SC, "Seychelles");
            yield return new CountryModel(CountryCode.SD, "Sudan");
            yield return new CountryModel(CountryCode.SE, "Sweden");
            yield return new CountryModel(CountryCode.SG, "Singapore");
            yield return new CountryModel(CountryCode.SH, "Saint Helena, Ascension and Tristan da Cunha");
            yield return new CountryModel(CountryCode.SI, "Slovenia");
            yield return new CountryModel(CountryCode.SJ, "Svalbard and Jan Mayen");
            yield return new CountryModel(CountryCode.SK, "Slovakia");
            yield return new CountryModel(CountryCode.SL, "Sierra Leone");
            yield return new CountryModel(CountryCode.SM, "San Marino");
            yield return new CountryModel(CountryCode.SN, "Senegal");
            yield return new CountryModel(CountryCode.SO, "Somalia");
            yield return new CountryModel(CountryCode.SR, "Suriname");
            yield return new CountryModel(CountryCode.SS, "South Sudan");
            yield return new CountryModel(CountryCode.ST, "Sao Tome and Principe");
            yield return new CountryModel(CountryCode.SV, "El Salvador");
            yield return new CountryModel(CountryCode.SX, "Sint Maarten (Dutch part)");
            yield return new CountryModel(CountryCode.SY, "Syrian Arab Republic");
            yield return new CountryModel(CountryCode.SZ, "Swaziland");
            yield return new CountryModel(CountryCode.TC, "Turks and Caicos Islands");
            yield return new CountryModel(CountryCode.TD, "Chad");
            yield return new CountryModel(CountryCode.TF, "French Southern Territories");
            yield return new CountryModel(CountryCode.TG, "Togo");
            yield return new CountryModel(CountryCode.TH, "Thailand");
            yield return new CountryModel(CountryCode.TJ, "Tajikistan");
            yield return new CountryModel(CountryCode.TK, "Tokelau");
            yield return new CountryModel(CountryCode.TL, "East Timor");
            yield return new CountryModel(CountryCode.TM, "Turkmenistan");
            yield return new CountryModel(CountryCode.TN, "Tunisia");
            yield return new CountryModel(CountryCode.TO, "Tonga");
            yield return new CountryModel(CountryCode.TR, "Turkey");
            yield return new CountryModel(CountryCode.TT, "Trinidad and Tobago");
            yield return new CountryModel(CountryCode.TV, "Tuvalu");
            yield return new CountryModel(CountryCode.TW, "Taiwan, Province of China[a]");
            yield return new CountryModel(CountryCode.TZ, "Tanzania, United Republic of");
            yield return new CountryModel(CountryCode.UA, "Ukraine");
            yield return new CountryModel(CountryCode.UG, "Uganda");
            yield return new CountryModel(CountryCode.UM, "United States Minor Outlying Islands");
            yield return new CountryModel(CountryCode.US, "United States of America");
            yield return new CountryModel(CountryCode.UY, "Uruguay");
            yield return new CountryModel(CountryCode.UZ, "Uzbekistan");
            yield return new CountryModel(CountryCode.VA, "Vatican City Holy See");
            yield return new CountryModel(CountryCode.VC, "Saint Vincent and the Grenadines");
            yield return new CountryModel(CountryCode.VE, "Venezuela (Bolivarian Republic of)");
            yield return new CountryModel(CountryCode.VG, "Virgin Islands (British)");
            yield return new CountryModel(CountryCode.VI, "Virgin Islands (U.S.)");
            yield return new CountryModel(CountryCode.VN, "Viet Nam");
            yield return new CountryModel(CountryCode.VU, "Vanuatu");
            yield return new CountryModel(CountryCode.WF, "Wallis and Futuna");
            yield return new CountryModel(CountryCode.WS, "Samoa");
            yield return new CountryModel(CountryCode.XK, "Kosovo");
            yield return new CountryModel(CountryCode.YE, "Yemen");
            yield return new CountryModel(CountryCode.YT, "Mayotte");
            yield return new CountryModel(CountryCode.ZA, "South Africa");
            yield return new CountryModel(CountryCode.ZM, "Zambia");
            yield return new CountryModel(CountryCode.ZW, "Zimbabwe");
        }
    }
}